# Generated by Django 4.2.7 on 2026-03-30 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('avg_temperature', models.FloatField()),
                ('avg_rainfall', models.FloatField()),
                ('avg_humidity', models.FloatField()),
            ],
            options={
                'unique_together': {('state', 'district', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('land_area', models.FloatField(default=1.0, help_text='Land area in acres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='N content in soil (kg/ha)')),
                ('phosphorus', models.FloatField(help_text='P content in soil (kg/ha)')),
                ('potassium', models.FloatField(help_text='K content in soil (kg/ha)')),
                ('ph_value', models.FloatField(help_text='Soil pH (0-14)')),
                ('rainfall', models.FloatField(help_text='Average rainfall in mm')),
                ('temperature', models.FloatField(help_text='Average temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('season', models.CharField(choices=[('kharif', 'Kharif (June-Nov)'), ('rabi', 'Rabi (Nov-April)'), ('zaid', 'Zaid (March-June)')], default='kharif', max_length=20)),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('top_3_crops', models.JSONField(default=list)),
                ('predicted_yield', models.FloatField(blank=True, help_text='Predicted yield in kg/acre', null=True)),
                ('yield_category', models.CharField(default='medium', max_length=20)),
                ('fertilizer_suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
